[build]
  publish = "dist"  # Or "public", depending on your build output
  command = "npm run build" # Or "yarn build", "hugo", etc.

[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301

[[headers]]
  # Define which paths this specific header configuration will apply to.
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'"